# Usa una imagen de Go como base
FROM golang:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /var/golang

# Mantén el contenedor en ejecución con un comando que se ejecute continuamente
CMD ["tail", "-f", "/dev/null"]
